###NLP Pipeline - Data Preprocessing
Week 2 NLP Pipeline PBA/ Genap 2025/ Irmasari Hafidz irma@its.ac.id

* Punctuations Removal
* Expand Contractions
* Spelling Correction
* Rare Words Removal
* Common Words Removal

In [1]:
!pip install contractions
!pip install textblob

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.0-cp313-cp313-win_amd64.whl.metadata (14 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
Downloading pyahocorasick-2.3.0-cp313-cp313-win_amd64.whl (35 kB)
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions

   ---------- ----------------------------- 1/4 [anyascii]
   ---------- ----------------------------- 1/4 [anyascii]
   ------------------------------ --------- 3/4 [contractions]
   ---------------------------------------- 4/4 [contractions]

Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.0 textsearch-0.0.24
Requirement already satisfied: textblob in c:\Users\isan40\anaconda3\Lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\Users\isan40\anaconda3\Lib\site-packages (from textblob) (3.9.2)
Requirement already satisfied: click in c:\Users\isan40\anaconda3\Lib\site-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in c:\Users\isan40\anaconda3\Lib\site-packages (from nltk>=3.9->textblob) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\isan40\anaconda3\Lib\site-packages (from nltk>=3.9->textblob) (2026.3.32)
Requirement already satisfied: tqdm in c:\Users\isan40\anaconda3\Lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\Users\isan40\anaconda3\Lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)

In [11]:
import pandas as pd
import re
from contractions import fix
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords
from collections import Counter
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

In [3]:
df = pd.read_csv('data.csv')
df.head()

                                             content    label
0  I like the game and is have funny legend and s...  Positif
1  I just retrieved my acc, great customer servic...  Positif
2                                          good game  Positif
3                                          it's best  Positif
4                                               good  Positif

In [12]:
def remove_punctuation(text):
    return re.sub(r'[^\w\s]', '', text)

def expand_contractions(text):
    return fix(text)

def correct_spelling(text):
    return str(TextBlob(text).correct())

def remove_rare_words(words, threshold=1):
    word_counts = Counter(words)
    return [word for word in words if word_counts[word] > threshold]

def remove_common_words(words, common_words):
    return [word for word in words if word not in common_words]

stemmer = PorterStemmer()

In [6]:
nltk.download('stopwords')
common_words_en = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to C:\Users\HP
[nltk_data]     840\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [13]:
df["remove_punctuation"] = df["content"].apply(lambda x: remove_punctuation(x))
df["expand_contractions"] = df["content"].apply(lambda x: expand_contractions(x))
df["correct_spelling"] = df["content"].apply(lambda x: correct_spelling(x))

nltk.download('punkt_tab')
df["tokens"] = df["content"].apply(lambda x: nltk.word_tokenize(x))
df["porter_stem"] = df["tokens"].apply(lambda x: [stemmer.stem(word) for word in x])

df["remove_rare_words"] = df["porter_stem"].apply(lambda x: remove_rare_words(x))
df["remove_common_words"] = df["porter_stem"].apply(lambda x: remove_common_words(x, common_words_en))

[nltk_data] Downloading package punkt_tab to C:\Users\HP
[nltk_data]     840\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [14]:
df.head()

,content,label,remove_punctuation,expand_contractions,correct_spelling,remove_rare_words,remove_common_words,tokens,porter_stem
0,I like the game and is have funny legend and s...,Positif,I like the game and is have funny legend and s...,I like the game and is have funny legend and s...,I like the game and is have funny legend and s...,"[i, the, and, is, have, and, my, of, the, you,...","[like, game, funni, legend, cool, skin, tone, ...","[I, like, the, game, and, is, have, funny, leg...","[i, like, the, game, and, is, have, funni, leg..."
1,"I just retrieved my acc, great customer servic...",Positif,I just retrieved my acc great customer service...,"I just retrieved my acc, great customer servic...","I just retrieved my act, great customer servic...",[],"[retriev, acc, ,, great, custom, servic, ., re...","[I, just, retrieved, my, acc, ,, great, custom...","[i, just, retriev, my, acc, ,, great, custom, ..."
2,good game,Positif,good game,good game,good game,[],"[good, game]","[good, game]","[good, game]"
3,it's best,Positif,its best,it is best,it's best,[],"['s, best]","[it, 's, best]","[it, 's, best]"
4,good,Positif,good,good,good,[],[good],[good],[good]