#Tokenization Techniques in NLP
Week 2 NLP Pipeline
PBA/ Genap 2025/ Irmasari Hafidz
irma@its.ac.id

## Install Dependencies

In [18]:
!pip install nltk
!pip install spacy sacremoses sentencepiece
!pip install transformers

! python3 -m spacy download en_core_web_sm

from spacy.lang.en import English
nlp = English()

Requirement already satisfied: nltk in c:\Users\isan40\anaconda3\Lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\Users\isan40\anaconda3\Lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\Users\isan40\anaconda3\Lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\isan40\anaconda3\Lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in c:\Users\isan40\anaconda3\Lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\Users\isan40\anaconda3\Lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: spacy in c:\Users\isan40\anaconda3\Lib\site-packages (3.8.11)
Requirement already satisfied: sacremoses in c:\Users\isan40\anaconda3\Lib\site-packages (0.1.1)
Requirement already satisfied: sentencepiece in c:\Users\isan40\anaconda3\Lib\site-packages (0.2.1)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (2.3.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (2.12.4)
Requirement already satisfied: jinja2 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\Users\isan40\anaconda3\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\Users\isan40\anaconda3\Lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\isan40\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\isan40\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\isan40\anaconda3\Lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.11.12)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\Users\isan40\anaconda3\Lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: typer>=0.24.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: wrapt in c:\Users\isan40\anaconda3\Lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (1.17.0)
Requirement already satisfied: regex in c:\Users\isan40\anaconda3\Lib\site-packages (from sacremoses) (2025.9.1)
Requirement already satisfied: click in c:\Users\isan40\anaconda3\Lib\site-packages (from sacremoses) (8.2.1)
Requirement already satisfied: joblib in c:\Users\isan40\anaconda3\Lib\site-packages (from sacremoses) (1.5.2)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\isan40\anaconda3\Lib\site-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from jinja2->spacy) (3.0.2)
Collecting transformers
  Downloading transformers-5.4.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.8.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in c:\Users\isan40\anaconda3\Lib\site-packages (from transformers) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.3.32-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\Users\isan40\anaconda3\Lib\site-packages (from transformers) (0.24.1)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.27 in c:\Users\isan40\anaconda3\Lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock>=3.10.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.0)
Collecting hf-xet<2.0.0,>=1.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\Users\isan40\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.10.0)
Requirement already satisfied: certifi in c:\Users\isan40\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\Users\isan40\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\Users\isan40\anaconda3\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\Users\isan40\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: colorama in c:\Users\isan40\anaconda3\Lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Requirement already satisfied: click>=8.2.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from typer->transformers) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from typer->transformers) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\Users\isan40\anaconda3\Lib\site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from rich>=12.3.0->typer->transformers) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\isan40\anaconda3\Lib\site-packages (from rich>=12.3.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\Users\isan40\anaconda3\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.4.0-py3-none-any.whl (10.1 MB)
   ---------------------------------------- 0.0/10.1 MB ? eta -:--:--
   ---------- ----------------------------- 2.6/10.1 MB 17.1 MB/s eta 0:00:01
   ---------------- ----------------------- 4.2/10.1 MB 13.5 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/10.1 MB 14.0 MB/s eta 0:00:01
   ---------------------------------------- 10.1/10.1 MB 14.4 MB/s  0:00:00
Downloading huggingface_hub-1.8.0-py3-none-any.whl (625 kB)
   ---------------------------------------- 0.0/625.2 kB ? eta -:--:--
   ---------------------------------------- 625.2/625.2 kB 15.1 MB/s  0:00:00
Downloading hf_xet-1.4.2-cp37-abi3-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ------------------------------- -------- 2.9/3.7 MB 14.6 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 13.3 MB/s  0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   -------------------------------------- - 2.6/2.7 MB 13.1 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 11.0 MB/s  0:00:00
Downloading regex-2026.3.32-cp313-cp313-win_amd64.whl (277 kB)
Downloading safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Installing collected packages: safetensors, regex, hf-xet, huggingface-hub, tokenizers, transformers

  Attempting uninstall: regex

    Found existing installation: regex 2025.9.1

    Uninstalling regex-2025.9.1:

      Successfully uninstalled regex-2025.9.1

   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   ------ --------------------------------- 1/6 [regex]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------- ------------------- 3/6 [huggingface-hub]
   -------------------------- ------------- 4/6 [tokenizers]
   -------------------------- ------------- 4/6 [tokenizers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]
   --------------------------------- ------ 5/6 [transformers]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\isan40\anaconda3\Lib\site-packages\~egex'.
  You can safely remove it manually.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Apps > Advanced app settings > App execution aliases.

## Import Required Libraries

In [1]:
import nltk
import spacy
import re
from nltk.tokenize import word_tokenize, sent_tokenize, RegexpTokenizer
from nltk.tokenize.treebank import TreebankWordTokenizer
from sacremoses import MosesTokenizer
import sentencepiece as spm
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
print(df.head())

                                             content    label
0  I like the game and is have funny legend and s...  Positif
1  I just retrieved my acc, great customer servic...  Positif
2                                          good game  Positif
3                                          it's best  Positif
4                                               good  Positif

### White Space Tokenization
*   one of the simplest tokenization techniques as it uses whitespace within the string as the delimiter of words.
*   Wherever the white space is, it will split the data at that point
*   Using **Python built** .split() in or **Spacy**

```
# sentence.split()
```

In [3]:
df["split_tokens"] = df["content"].apply(lambda x: x.split())
df["split_tokens"]

0      [I, like, the, game, and, is, have, funny, leg...
1      [I, just, retrieved, my, acc,, great, customer...
2                                           [good, game]
3                                           [it's, best]
4                                                 [good]
                             ...
169    [i, love, mlbb, but, I'll, hope, I, got, luckk...
170    [An, appeal, should, be, validated, by, Moonto...
171    [Very, very, awesome, and, fun, to, play,, but...
172    [The, game, improved, a, lot, in, all, areas,,...
173    [my, first, MOBA, game,, it's, not, that, bad,...
Name: split_tokens, Length: 174, dtype: object

In [5]:
from nltk.tokenize import WhitespaceTokenizer

# Create a reference variable for Class WhitespaceTokenizer
wtk = WhitespaceTokenizer()

#use tokenize method
df["whitespace_tokens"] = df["content"].apply(lambda x: wtk.tokenize(x))
df["whitespace_tokens"]

0      [I, like, the, game, and, is, have, funny, leg...
1      [I, just, retrieved, my, acc,, great, customer...
2                                           [good, game]
3                                           [it's, best]
4                                                 [good]
                             ...
169    [i, love, mlbb, but, I'll, hope, I, got, luckk...
170    [An, appeal, should, be, validated, by, Moonto...
171    [Very, very, awesome, and, fun, to, play,, but...
172    [The, game, improved, a, lot, in, all, areas,,...
173    [my, first, MOBA, game,, it's, not, that, bad,...
Name: whitespace_tokens, Length: 174, dtype: object

#### **Tokenization** using Spacy and NLTK

Word level Tokenization

In [8]:
import spacy

nlp = spacy.load('en_core_web_sm')

def spacy_token(text):
  doc= nlp(text)
  return [token.text for token in doc]

df["spacy_tokens"] = df["content"].apply(spacy_token)
df[["content", "spacy_tokens"]].head()

,content,spacy_tokens
0,I like the game and is have funny legend and s...,"[I, like, the, game, and, is, have, funny, leg..."
1,"I just retrieved my acc, great customer servic...","[I, just, retrieved, my, acc, ,, great, custom..."
2,good game,"[good, game]"
3,it's best,"[it, 's, best]"
4,good,[good]

In [9]:
from nltk.tokenize import word_tokenize
nltk.download('punkt_tab')
df["nltk_tokens"] = df["content"].apply(lambda x: word_tokenize(x))
df["nltk_tokens"].head()

[nltk_data] Downloading package punkt_tab to C:\Users\HP
[nltk_data]     840\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

0    [I, like, the, game, and, is, have, funny, leg...
1    [I, just, retrieved, my, acc, ,, great, custom...
2                                         [good, game]
3                                       [it, 's, best]
4                                               [good]
Name: nltk_tokens, dtype: object

In [15]:
#import sent_tokenize from nltk library
from nltk import sent_tokenize
def tokenize_process(text):
    # Pecah jadi kalimat, lalu tiap kalimat dipecah jadi kata
    return [word_tokenize(sent) for sent in sent_tokenize(text)]

df['sent_tokenize'] = df['content'].apply(tokenize_process)
df['sent_tokenize'][1]

[['I',
  'just',
  'retrieved',
  'my',
  'acc',
  ',',
  'great',
  'customer',
  'services',
  '.'],
 ['It', 'really', 'helped', 'me', 'alot']]

Character Tokenization

In [ ]:
text = "Jerman"
characters = list(text)
print("Character Tokens:", characters)

Character Tokens: ['J', 'e', 'r', 'm', 'a', 'n']

Subword Tokenization

*   breaks down words into smaller units called subwords.
*   used to handle unknown or rare words by breaking them into small known words.

In [20]:
from transformers import BertTokenizer

bert = BertTokenizer.from_pretrained('bert-base-uncased')

df["bert_tokens"] = df["content"].apply(lambda x: bert.tokenize(x))
df["bert_tokens"].head()

0    [i, like, the, game, and, is, have, funny, leg...
1    [i, just, retrieved, my, acc, ,, great, custom...
2                                         [good, game]
3                                     [it, ', s, best]
4                                               [good]
Name: bert_tokens, dtype: object

In [ ]:
import nltk
import spacy
import re
from nltk.tokenize import word_tokenize, sent_tokenize, RegexpTokenizer
from nltk.tokenize.treebank import TreebankWordTokenizer
from sacremoses import MosesTokenizer
import sentencepiece as spm

# White Space Tokenization
def whitespace_tokenization(text):
    return text.split()

# Regular Expression Tokenizer
def regex_tokenization(text):
    tokenizer = RegexpTokenizer(r'\w+')
    return tokenizer.tokenize(text)

# Penn Treebank Tokenization
def penn_treebank_tokenization(text):
    tokenizer = TreebankWordTokenizer()
    return tokenizer.tokenize(text)

# SpaCy Tokenization
nlp = spacy.load("en_core_web_sm")
def spacy_tokenization(text):
    doc = nlp(text)
    return [token.text for token in doc]

# Moses Tokenization
moses_tokenizer = MosesTokenizer()
def moses_tokenization(text):
    return moses_tokenizer.tokenize(text)

In [21]:
df.head()

,content,label,split_tokens,whitespace_tokens,spacy_tokens,nltk_tokens,tokenized_content,sent_tokenize,bert_tokens
0,I like the game and is have funny legend and s...,Positif,"[I, like, the, game, and, is, have, funny, leg...","[I, like, the, game, and, is, have, funny, leg...","[I, like, the, game, and, is, have, funny, leg...","[I, like, the, game, and, is, have, funny, leg...","[[I, like, the, game, and, is, have, funny, le...","[[I, like, the, game, and, is, have, funny, le...","[i, like, the, game, and, is, have, funny, leg..."
1,"I just retrieved my acc, great customer servic...",Positif,"[I, just, retrieved, my, acc,, great, customer...","[I, just, retrieved, my, acc,, great, customer...","[I, just, retrieved, my, acc, ,, great, custom...","[I, just, retrieved, my, acc, ,, great, custom...","[[I, just, retrieved, my, acc, ,, great, custo...","[[I, just, retrieved, my, acc, ,, great, custo...","[i, just, retrieved, my, acc, ,, great, custom..."
2,good game,Positif,"[good, game]","[good, game]","[good, game]","[good, game]","[[good, game]]","[[good, game]]","[good, game]"
3,it's best,Positif,"[it's, best]","[it's, best]","[it, 's, best]","[it, 's, best]","[[it, 's, best]]","[[it, 's, best]]","[it, ', s, best]"
4,good,Positif,[good],[good],[good],[good],[[good]],[[good]],[good]